import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "./supabase";

type Listing={id:string;title:string;description?:string|null;price:number;quantity:number;location?:string|null;images?:string[]|null;category_id?:string|null;seller_id:string;created_at:string;status?:string;categories?:{name:string}|null;profiles?:{full_name:string|null;school:string|null}|null};
type Category={id:string;name:string};
type View="home"|"sell"|"orders"|"saved"|"account"|"listing"|"manage";

const demoCategories:Category[]=[{id:"all",name:"All"},{id:"electronics",name:"Electronics"},{id:"fashion",name:"Fashion"},{id:"books",name:"Books"},{id:"services",name:"Services"},{id:"hostel",name:"Hostel & Home"},{id:"food",name:"Food"}];
const demo:Listing[]=[
{id:"demo-1",title:"Clean HP laptop charger",description:"Genuine charger in good working condition.",price:120,quantity:1,location:"UG Legon",images:[],category_id:"electronics",seller_id:"demo",created_at:"2026-09-19T10:00:00Z",categories:{name:"Electronics"},profiles:{full_name:"Campus Seller",school:"University of Ghana"}},
{id:"demo-2",title:"Second-hand textbooks",description:"Useful course textbooks at student-friendly prices.",price:45,quantity:4,location:"KNUST",images:[],category_id:"books",seller_id:"demo",created_at:"2026-09-18T10:00:00Z",categories:{name:"Books"},profiles:{full_name:"Student Books",school:"KNUST"}},
{id:"demo-3",title:"Braids & protective styling",description:"Book a student-friendly styling service.",price:80,quantity:3,location:"Accra",images:[],category_id:"services",seller_id:"demo",created_at:"2026-09-17T10:00:00Z",categories:{name:"Services"},profiles:{full_name:"Campus Stylist",school:"Accra"}},
{id:"demo-4",title:"Campus hoodie",description:"Comfortable everyday hoodie.",price:95,quantity:2,location:"UPSA",images:[],category_id:"fashion",seller_id:"demo",created_at:"2026-09-16T10:00:00Z",categories:{name:"Fashion"},profiles:{full_name:"Campus Wear",school:"UPSA"}}
];
const money=(n:number)=>new Intl.NumberFormat("en-GH",{style:"currency",currency:"GHS",maximumFractionDigits:2}).format(Number(n)||0);
const savedKey="students-business:saved";

export default function App(){
 const [session,setSession]=useState<any>(null),[listings,setListings]=useState<Listing[]>(demo),[categories,setCategories]=useState<Category[]>(demoCategories.slice(1));
 const [view,setView]=useState<View>("home"),[selected,setSelected]=useState<Listing|null>(null),[query,setQuery]=useState(""),[cat,setCat]=useState("all"),[sort,setSort]=useState("newest"),[notice,setNotice]=useState("");
 const [saved,setSaved]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem(savedKey)||"[]")}catch{return[]}});
 const [loading,setLoading]=useState(false);
 const go=(v:View,l?:Listing)=>{setSelected(l||null);setView(v);window.scrollTo({top:0,behavior:"smooth"})};
 const refresh=async()=>{
   setLoading(true);
   try{
    const [a,b]=await Promise.all([
      supabase.from("listings").select("*, categories(name), profiles(full_name,school)").eq("status","active").order("created_at",{ascending:false}),
      supabase.from("categories").select("id,name").order("name")
    ]);
    if(!a.error&&a.data?.length)setListings(a.data as Listing[]);
    if(!b.error&&b.data?.length)setCategories(b.data as Category[]);
   }catch{}
   setLoading(false);
 };
 useEffect(()=>{refresh();supabase.auth.getSession().then(x=>setSession(x.data.session)).catch(()=>{});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(""),4500);return()=>clearTimeout(t)}},[notice]);
 const filtered=useMemo(()=>listings.filter(l=>{
   const text=`${l.title} ${l.description||""} ${l.location||""} ${l.categories?.name||""}`.toLowerCase();
   return (!query||text.includes(query.toLowerCase()))&&(cat==="all"||l.category_id===cat);
 }).sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:new Date(b.created_at).getTime()-new Date(a.created_at).getTime()),[listings,query,cat,sort]);
 const toggleSave=(id:string)=>{const n=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(n);localStorage.setItem(savedKey,JSON.stringify(n))};
 const auth=(v:View)=>session?go(v):go("account");
 return <div className="app">
  <header className="topbar"><button className="brand" onClick={()=>go("home")}><span>SB</span><b>Students Business</b></button><nav><button className={view==="home"?"active":""} onClick={()=>go("home")}>Discover</button><button onClick={()=>auth("sell")}>Sell</button><button onClick={()=>auth("orders")}>Orders</button><button onClick={()=>go("saved")}>Saved {saved.length>0&&<i>{saved.length}</i>}</button></nav><button className="account" onClick={()=>go("account")}>{session?"Account":"Sign in"}</button></header>
  {notice&&<div className="notice" onClick={()=>setNotice("")}>{notice}</div>}
  {view==="home"&&<Home query={query} setQuery={setQuery} cat={cat} setCat={setCat} sort={sort} setSort={setSort} categories={categories} listings={filtered} loading={loading} saved={saved} open={(l:Listing)=>go("listing",l)} save={toggleSave} sell={()=>auth("sell")}/>}
  {view==="listing"&&selected&&<ListingPage l={selected} session={session} saved={saved.includes(selected.id)} save={()=>toggleSave(selected.id)} back={()=>go("home")} notice={setNotice}/>}
  {view==="sell"&&<Sell session={session} categories={categories} done={refresh} notice={setNotice} account={()=>go("account")} manage={()=>go("manage")}/>}
  {view==="orders"&&<Orders session={session}/>}
  {view==="saved"&&<Saved listings={listings.filter(l=>saved.includes(l.id))} open={(l:Listing)=>go("listing",l)} save={toggleSave}/>}
  {view==="manage"&&<Manage session={session} listings={listings} done={refresh} notice={setNotice}/>}
  {view==="account"&&<Account session={session} notice={setNotice} signOut={async()=>{await supabase.auth.signOut().catch(()=>{});setSession(null);go("home")}} manage={()=>auth("manage")}/>}
  <footer><b>Students Business</b><span>Buy smarter. Sell faster. Built for student life.</span></footer>
  <div className="bottom"><button onClick={()=>go("home")}>⌂<small>Home</small></button><button onClick={()=>auth("sell")}>＋<small>Sell</small></button><button onClick={()=>auth("orders")}>▣<small>Orders</small></button><button onClick={()=>go("saved")}>♡<small>Saved</small></button><button onClick={()=>go("account")}>◯<small>Account</small></button></div>
 </div>
}

function Home(p:any){return <main><section className="hero"><div><label>CAMPUS MARKETPLACE</label><h1>Find it. Sell it.<br/><em>Keep it simple.</em></h1><p>Students Business connects students with useful products and services around campus, with clear prices and simple discovery.</p><div className="actions"><button className="primary" onClick={()=>document.getElementById("market")?.scrollIntoView({behavior:"smooth"})}>Explore marketplace →</button><button className="secondary" onClick={p.sell}>Start selling</button></div></div><aside><small>WHY STUDENTS BUSINESS</small><strong>One place for<br/>student-to-student commerce.</strong><span>✓ Student-focused discovery</span><span>✓ Clear pricing</span><span>✓ Seller profiles</span><span>✓ Save what you like</span></aside></section>
<section className="section categories"><div><label>SHOP BY CATEGORY</label><h2>What do you need?</h2></div><div className="chips"><button className={p.cat==="all"?"selected":""} onClick={()=>p.setCat("all")}>All</button>{p.categories.map((c:Category)=><button key={c.id} className={p.cat===c.id?"selected":""} onClick={()=>p.setCat(c.id)}>{c.name}</button>)}</div></section>
<section className="section" id="market"><div className="heading"><div><label>DISCOVER</label><h2>Latest listings</h2></div><span>{p.listings.length} results</span></div><div className="filters"><div className="search">⌕<input value={p.query} onChange={(e:any)=>p.setQuery(e.target.value)} placeholder="Search products, services or locations"/></div><select value={p.sort} onChange={(e:any)=>p.setSort(e.target.value)}><option value="newest">Newest</option><option value="low">Lowest price</option><option value="high">Highest price</option></select></div>{p.loading&&<div className="loading">Loading live listings…</div>}{!p.loading&&!p.listings.length&&<div className="empty"><b>No matching listings</b><span>Try another search or category.</span></div>}<div className="grid">{p.listings.map((l:Listing)=><Card key={l.id} l={l} saved={p.saved.includes(l.id)} open={()=>p.open(l)} save={()=>p.save(l.id)}/>)}</div></section></main>}

function Card({l,saved,open,save}:{l:Listing;saved:boolean;open:()=>void;save:()=>void}){return <article className="card"><button className="heart" onClick={e=>{e.stopPropagation();save()}}>{saved?"♥":"♡"}</button><button className="pic" onClick={open}>{l.images?.[0]?<img src={l.images[0]} alt=""/>:<span>{(l.categories?.name||"SB").slice(0,2).toUpperCase()}</span>}</button><button className="cardbody" onClick={open}><label>{l.categories?.name||"Marketplace"}</label><h3>{l.title}</h3><b>{money(l.price)}</b><small>⌖ {l.location||"Campus"} · {l.quantity} available</small></button></article>}

function ListingPage({l,session,saved,save,back,notice}:{l:Listing;session:any;saved:boolean;save:()=>void;back:()=>void;notice:(s:string)=>void}){const[q,setQ]=useState(1),[busy,setBusy]=useState(false);const buy=async()=>{if(!session){notice("Sign in before placing an order.");return}setBusy(true);const r=await supabase.rpc("create_order",{p_listing_id:l.id,p_quantity:q,p_delivery_location:l.location||null,p_buyer_note:null});setBusy(false);if(r.error)notice(r.error.message);else{notice("Order placed successfully.");back()}};return <main className="page"><button className="back" onClick={back}>← Marketplace</button><div className="detail"><div className="detailpic">{l.images?.[0]?<img src={l.images[0]} alt=""/>:<span>{(l.categories?.name||"SB").slice(0,2).toUpperCase()}</span>}</div><div className="detailtext"><label>{l.categories?.name||"Marketplace"}</label><h1>{l.title}</h1><strong className="price">{money(l.price)}</strong><p>{l.description||"A student listing available on the marketplace."}</p><div className="seller"><span>{(l.profiles?.full_name||"S").slice(0,1)}</span><div><b>{l.profiles?.full_name||"Student seller"}</b><small>{l.profiles?.school||"Student"} · {l.location||"Campus"}</small></div></div><div className="buy"><div><button onClick={()=>setQ(Math.max(1,q-1))}>−</button><b>{q}</b><button onClick={()=>setQ(Math.min(l.quantity,q+1))}>+</button></div><button className="primary grow" disabled={busy} onClick={buy}>{busy?"Placing order…":"Place order · "+money(l.price*q)}</button><button className="savebtn" onClick={save}>{saved?"♥":"♡"}</button></div><div className="trust"><b>✓ Buy with confidence</b><span>Confirm the seller and arrange a safe campus handoff before payment.</span></div></div></div></main>}

function Sell({session,categories,done,notice,account,manage}:{session:any;categories:Category[];done:()=>void;notice:(s:string)=>void;account:()=>void;manage:()=>void}){const[f,setF]=useState({title:"",description:"",price:"",quantity:"1",category_id:"",location:"",image:""}),[busy,setBusy]=useState(false);if(!session)return <main className="page"><div className="empty"><b>Sign in to sell</b><span>Create an account and publish your first listing.</span><button className="primary" onClick={account}>Sign in / create account</button></div></main>;const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);const r=await supabase.from("listings").insert({seller_id:session.user.id,title:f.title,description:f.description||null,price:Number(f.price),quantity:Number(f.quantity),category_id:f.category_id||null,location:f.location||null,images:f.image?[f.image]:[],status:"active"});setBusy(false);if(r.error)notice(r.error.message);else{notice("Listing published.");done();manage()}};return <main className="page narrow"><label>SELL ON STUDENTS BUSINESS</label><h1>Create a listing</h1><p className="lead">Give another student enough information to buy confidently.</p><form className="form" onSubmit={submit}><label>Title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="e.g. Calculator, hoodie, tutoring"/></label><label>Description<textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})} placeholder="Condition, details, what is included…"/></label><div className="two"><label>Price (GHS)<input required type="number" min="0" step=".01" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/></label><label>Quantity<input required type="number" min="1" value={f.quantity} onChange={e=>setF({...f,quantity:e.target.value})}/></label></div><div className="two"><label>Category<select value={f.category_id} onChange={e=>setF({...f,category_id:e.target.value})}><option value="">Choose one</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Location<input value={f.location} onChange={e=>setF({...f,location:e.target.value})} placeholder="Campus / area"/></label></div><label>Image URL <small>optional</small><input type="url" value={f.image} onChange={e=>setF({...f,image:e.target.value})} placeholder="https://…"/></label><button className="primary" disabled={busy}>{busy?"Publishing…":"Publish listing →"}</button></form></main>}

function Orders({session}:{session:any}){const[data,setData]=useState<any[]>([]);useEffect(()=>{if(session)supabase.from("orders").select("id,quantity,total_amount,status,created_at,listings(title)").eq("buyer_id",session.user.id).order("created_at",{ascending:false}).then(r=>setData(r.data||[]))},[session]);if(!session)return <main className="page"><div className="empty"><b>Your orders are private.</b><span>Sign in to view your purchases.</span></div></main>;return <main className="page"><label>YOUR ACTIVITY</label><h1>Orders</h1><div className="list">{data.length?data.map(o=><div className="row" key={o.id}><div><b>{o.listings?.title||"Order"}</b><small>#{String(o.id).slice(0,8)} · {new Date(o.created_at).toLocaleDateString()}</small></div><strong>{money(o.total_amount)}</strong><span>{o.status}</span></div>):<div className="empty"><b>No orders yet.</b><span>Your purchases will appear here.</span></div>}</div></main>}

function Saved({listings,open,save}:{listings:Listing[];open:(l:Listing)=>void;save:(id:string)=>void}){return <main className="page"><label>YOUR PICKS</label><h1>Saved listings</h1>{listings.length?<div className="grid">{listings.map(l=><Card key={l.id} l={l} saved open={()=>open(l)} save={()=>save(l.id)}/>)}</div>:<div className="empty"><b>Nothing saved yet.</b><span>Tap the heart on any listing to keep it here.</span></div>}</main>}

function Manage({session,listings,done,notice}:{session:any;listings:Listing[];done:()=>void;notice:(s:string)=>void}){const mine=listings.filter(l=>l.seller_id===session?.user?.id);return <main className="page"><label>SELLER SPACE</label><h1>My listings</h1><div className="list">{mine.length?mine.map(l=><div className="row" key={l.id}><div><b>{l.title}</b><small>{money(l.price)} · {l.quantity} available</small></div><button className="danger" onClick={async()=>{const r=await supabase.from("listings").update({status:"inactive"}).eq("id",l.id);if(r.error)notice(r.error.message);else{notice("Listing removed.");done()}}}>Remove</button></div>):<div className="empty"><b>No active listings.</b><span>Your published items will appear here.</span></div>}</div></main>}

function Account({session,notice,signOut,manage}:{session:any;notice:(s:string)=>void;signOut:()=>void;manage:()=>void}){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[signup,setSignup]=useState(false),[busy,setBusy]=useState(false);if(session)return <main className="page narrow"><div className="accountbox"><span className="avatar">{(session.user.email||"S")[0].toUpperCase()}</span><label>YOUR ACCOUNT</label><h1>{session.user.user_metadata?.full_name||"Student account"}</h1><p>{session.user.email}</p><button onClick={manage}>My listings</button><button className="danger" onClick={signOut}>Sign out</button></div></main>;const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);const r=signup?await supabase.auth.signUp({email,password,options:{data:{full_name:name}}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(r.error)notice(r.error.message);else notice(signup?"Account created. Check your email if confirmation is enabled.":"Signed in.")};return <main className="page narrow"><div className="auth"><span className="logoMark">SB</span><h1>{signup?"Join Students Business":"Welcome back"}</h1><p>Buy, sell and manage your campus marketplace activity.</p><form className="form" onSubmit={submit}>{signup&&<label>Name<input required value={name} onChange={e=>setName(e.target.value)}/></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?"Please wait…":signup?"Create account →":"Sign in →"}</button></form><button className="link" onClick={()=>setSignup(!signup)}>{signup?"Already have an account? Sign in":"New here? Create an account"}</button></div></main>}
