import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "./supabase";

type Listing={id:string;title:string;description?:string|null;price:number;quantity:number;location?:string|null;images?:string[]|null;category_id?:string|null;seller_id:string;created_at:string;status?:string;categories?:{name:string}|null;profiles?:{full_name:string|null;school:string|null}|null};
type Category={id:string;name:string};
type Tab="discover"|"sell"|"activity"|"saved"|"profile";

const categories:Category[]=[
{id:"all",name:"Everything"},{id:"electronics",name:"Electronics"},{id:"fashion",name:"Fashion"},
{id:"books",name:"Books & Study"},{id:"services",name:"Services"},{id:"hostel",name:"Hostel & Home"},{id:"food",name:"Food"}
];

const demo:Listing[]=[
{id:"d1",title:"HP Laptop Charger",description:"Original charger, tested and working. Ready for campus pickup.",price:120,quantity:1,location:"UG Legon",images:[],category_id:"electronics",seller_id:"demo",created_at:"2026-09-19T16:00:00Z",categories:{name:"Electronics"},profiles:{full_name:"Campus Tech",school:"University of Ghana"}},
{id:"d2",title:"Calculus & Statistics Textbooks",description:"Clean copies for students taking first and second year quantitative courses.",price:75,quantity:3,location:"KNUST",images:[],category_id:"books",seller_id:"demo",created_at:"2026-09-19T14:00:00Z",categories:{name:"Books & Study"},profiles:{full_name:"Kofi Books",school:"KNUST"}},
{id:"d3",title:"Student Braids",description:"Protective styling with campus-friendly booking and pricing.",price:80,quantity:4,location:"Accra",images:[],category_id:"services",seller_id:"demo",created_at:"2026-09-18T18:00:00Z",categories:{name:"Services"},profiles:{full_name:"Ama Styles",school:"Accra"}},
{id:"d4",title:"Oversized Campus Hoodie",description:"Soft everyday hoodie. Several sizes available.",price:95,quantity:5,location:"UPSA",images:[],category_id:"fashion",seller_id:"demo",created_at:"2026-09-18T12:00:00Z",categories:{name:"Fashion"},profiles:{full_name:"Campus Wear",school:"UPSA"}},
{id:"d5",title:"Mini Fridge",description:"Compact fridge suitable for a hostel room. Good working condition.",price:650,quantity:1,location:"Pentagon, KNUST",images:[],category_id:"hostel",seller_id:"demo",created_at:"2026-09-17T10:00:00Z",categories:{name:"Hostel & Home"},profiles:{full_name:"Hostel Finds",school:"KNUST"}},
{id:"d6",title:"Jollof + Chicken",description:"Fresh student meal. Order ahead for lunch pickup.",price:35,quantity:12,location:"Legon Campus",images:[],category_id:"food",seller_id:"demo",created_at:"2026-09-16T13:00:00Z",categories:{name:"Food"},profiles:{full_name:"Campus Kitchen",school:"UG"}}
];

const money=(n:number)=>new Intl.NumberFormat("en-GH",{style:"currency",currency:"GHS",maximumFractionDigits:2}).format(Number(n)||0);
const savedKey="students-business:saved";

export default function App(){
 const [tab,setTab]=useState<Tab>("discover"),[session,setSession]=useState<any>(null),[listings,setListings]=useState<Listing[]>(demo),[liveCats,setLiveCats]=useState<Category[]>(categories.slice(1));
 const [selected,setSelected]=useState<Listing|null>(null),[query,setQuery]=useState(""),[cat,setCat]=useState("all"),[sort,setSort]=useState("newest"),[saved,setSaved]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem(savedKey)||"[]")}catch{return[]}}),[notice,setNotice]=useState(""),[loading,setLoading]=useState(false);
 const refresh=async()=>{setLoading(true);try{const [a,b]=await Promise.all([supabase.from("listings").select("*, categories(name), profiles(full_name,school)").eq("status","active").order("created_at",{ascending:false}),supabase.from("categories").select("id,name").order("name")]);if(!a.error&&a.data?.length)setListings(a.data as Listing[]);if(!b.error&&b.data?.length)setLiveCats(b.data as Category[])}catch{}setLoading(false)};
 useEffect(()=>{refresh();supabase.auth.getSession().then(r=>setSession(r.data.session)).catch(()=>{});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(""),4000);return()=>clearTimeout(t)},[notice]);
 const filtered=useMemo(()=>listings.filter(l=>{const text=[l.title,l.description,l.location,l.categories?.name].join(" ").toLowerCase();return(!query||text.includes(query.toLowerCase()))&&(cat==="all"||l.category_id===cat)}).sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:new Date(b.created_at).getTime()-new Date(a.created_at).getTime()),[listings,query,cat,sort]);
 const toggleSave=(id:string)=>{const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);localStorage.setItem(savedKey,JSON.stringify(next))};
 const requireAuth=(next:Tab)=>{if(session)setTab(next);else setTab("profile")};
 const open=(l:Listing)=>{setSelected(l);window.scrollTo({top:0,behavior:"smooth"})};
 return <div className="app">
  <header className="nav"><button className="wordmark" onClick={()=>{setTab("discover");setSelected(null)}}><span>SB</span><b>Students Business</b></button><nav>{(["discover","sell","activity","saved"] as Tab[]).map(x=><button key={x} className={tab===x&&!selected?"active":""} onClick={()=>x==="sell"||x==="activity"?requireAuth(x):setTab(x)}>{x==="discover"?"Discover":x==="activity"?"Activity":x[0].toUpperCase()+x.slice(1)}</button>)}</nav><button className="profileBtn" onClick={()=>{setTab("profile");setSelected(null)}}>{session?"Profile":"Sign in"}</button></header>
  {notice&&<button className="toast" onClick={()=>setNotice("")}>{notice}</button>}
  {selected?<ListingDetail listing={selected} session={session} saved={saved.includes(selected.id)} save={()=>toggleSave(selected.id)} back={()=>setSelected(null)} notice={setNotice}/>:tab==="discover"?<Discover query={query} setQuery={setQuery} cat={cat} setCat={setCat} sort={sort} setSort={setSort} listings={filtered} categories={liveCats} saved={saved} save={toggleSave} open={open} loading={loading} sell={()=>requireAuth("sell")}/>:tab==="sell"?<Sell session={session} categories={liveCats} refresh={refresh} notice={setNotice} goProfile={()=>setTab("profile")} goActivity={()=>setTab("activity")}/>:tab==="activity"?<Activity session={session}/>:tab==="saved"?<Saved listings={listings.filter(l=>saved.includes(l.id))} open={open} save={toggleSave}/>:<Profile session={session} notice={setNotice} signOut={async()=>{await supabase.auth.signOut().catch(()=>{});setSession(null);setTab("discover")}} goActivity={()=>setTab("activity")}/>}
  <footer><div><b>Students Business</b><span>A trusted marketplace made around student life.</span></div><span>Buy locally · Sell simply · Connect safely</span></footer>
  <div className="mobileNav">{(["discover","sell","activity","saved","profile"] as const).map(x=><button key={x} onClick={()=>x==="sell"||x==="activity"?requireAuth(x):setTab(x as Tab)} className={tab===x&&!selected?"active":""}><strong>{x==="discover"?"⌂":x==="sell"?"＋":x==="activity"?"▣":x==="saved"?"♡":"◯"}</strong><small>{x==="discover"?"Home":x==="activity"?"Orders":x[0].toUpperCase()+x.slice(1)}</small></button>)}</div>
 </div>
}

function Discover(p:any){return <main>
 <section className="hero"><div className="heroCopy"><span className="eyebrow">THE STUDENT MARKETPLACE</span><h1>Everything you need.<br/><i>Closer to you.</i></h1><p>Find products, services, food and everyday essentials from people around your campus.</p><div className="heroActions"><button className="primary" onClick={()=>document.getElementById("listings")?.scrollIntoView({behavior:"smooth"})}>Start exploring</button><button className="ghost" onClick={p.sell}>I want to sell</button></div><div className="proof"><span><b>01</b> Discover</span><span><b>02</b> Connect</span><span><b>03</b> Buy or sell</span></div></div><div className="heroCard"><span>BUILT FOR CAMPUS</span><b>Good stuff<br/>should be easy<br/>to find.</b><small>Search by what you need, compare clear prices, then arrange a convenient handoff.</small></div></section>
 <section className="section" id="listings"><div className="sectionTop"><div><span className="eyebrow">EXPLORE</span><h2>What are you looking for?</h2></div><span className="count">{p.listings.length} listings</span></div>
 <div className="searchRow"><div className="searchBox"><span>⌕</span><input value={p.query} onChange={(e:any)=>p.setQuery(e.target.value)} placeholder="Search products, services, food or campus"/></div><select value={p.sort} onChange={(e:any)=>p.setSort(e.target.value)}><option value="newest">Newest</option><option value="low">Lowest price</option><option value="high">Highest price</option></select></div>
 <div className="categoryRail"><button className={p.cat==="all"?"chosen":""} onClick={()=>p.setCat("all")}>Everything</button>{p.categories.map((c:Category)=><button key={c.id} className={p.cat===c.id?"chosen":""} onClick={()=>p.setCat(c.id)}>{c.name}</button>)}</div>
 {p.loading?<div className="empty">Loading marketplace…</div>:!p.listings.length?<div className="empty"><b>No listings found</b><span>Try a different search or category.</span></div>:<div className="marketGrid">{p.listings.map((l:Listing)=><Product key={l.id} l={l} saved={p.saved.includes(l.id)} save={()=>p.save(l.id)} open={()=>p.open(l)}/>)}</div>}
 </section>
 <section className="trustStrip"><div><b>Student-first</b><span>Designed around campus buying and selling.</span></div><div><b>Clear pricing</b><span>See the price before you contact a seller.</span></div><div><b>Local discovery</b><span>Find useful things closer to where you study.</span></div></section>
 </main>}

function Product({l,saved,save,open}:{l:Listing;saved:boolean;save:()=>void;open:()=>void}){return <article className="product"><div className="productVisual"><button className="save" onClick={e=>{e.stopPropagation();save()}}>{saved?"♥":"♡"}</button><button onClick={open}>{l.images?.[0]?<img src={l.images[0]} alt=""/>:<span className="initial">{(l.categories?.name||"SB").slice(0,2).toUpperCase()}</span>}</button></div><button className="productInfo" onClick={open}><small>{l.categories?.name||"Marketplace"}</small><h3>{l.title}</h3><strong>{money(l.price)}</strong><span>⌖ {l.location||"Campus"} <i>·</i> {l.quantity} available</span></button></article>}

function ListingDetail({listing:l,session,saved,save,back,notice}:{listing:Listing;session:any;saved:boolean;save:()=>void;back:()=>void;notice:(s:string)=>void}){const[q,setQ]=useState(1),[busy,setBusy]=useState(false);const buy=async()=>{if(!session){notice("Sign in to place an order.");return}setBusy(true);const r=await supabase.rpc("create_order",{p_listing_id:l.id,p_quantity:q,p_delivery_location:l.location||null,p_buyer_note:null});setBusy(false);if(r.error)notice(r.error.message);else{notice("Order placed successfully.");back()}};return <main className="page"><button className="back" onClick={back}>← Back to marketplace</button><div className="detailCard"><div className="detailVisual">{l.images?.[0]?<img src={l.images[0]} alt=""/>:<span>{(l.categories?.name||"SB").slice(0,2).toUpperCase()}</span>}</div><div className="detailBody"><span className="eyebrow">{l.categories?.name||"MARKETPLACE"}</span><h1>{l.title}</h1><strong className="detailPrice">{money(l.price)}</strong><p>{l.description||"A student listing available through Students Business."}</p><div className="sellerLine"><span>{(l.profiles?.full_name||"S")[0]}</span><div><b>{l.profiles?.full_name||"Student seller"}</b><small>{l.profiles?.school||"Student"} · {l.location||"Campus"}</small></div></div><div className="purchase"><div className="qty"><button onClick={()=>setQ(Math.max(1,q-1))}>−</button><b>{q}</b><button onClick={()=>setQ(Math.min(l.quantity,q+1))}>+</button></div><button className="primary grow" disabled={busy||l.quantity<1} onClick={buy}>{busy?"Placing order…":"Place order · "+money(l.price*q)}</button><button className="iconBtn" onClick={save}>{saved?"♥":"♡"}</button></div><div className="safety"><b>Before you pay</b><span>Confirm the item, seller and handoff location. Keep exchanges in safe public campus areas.</span></div></div></div></main>}

function Sell({session,categories,refresh,notice,goProfile,goActivity}:{session:any;categories:Category[];refresh:()=>void;notice:(s:string)=>void;goProfile:()=>void;goActivity:()=>void}){const[f,setF]=useState({title:"",description:"",price:"",quantity:"1",category_id:"",location:"",image:""}),[busy,setBusy]=useState(false);if(!session)return <main className="page narrow"><div className="authCard"><span className="eyebrow">SELL ON STUDENTS BUSINESS</span><h1>Your next buyer is nearby.</h1><p>Sign in first, then create a clear listing in under a minute.</p><button className="primary" onClick={goProfile}>Sign in / create account</button></div></main>;const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);const r=await supabase.from("listings").insert({seller_id:session.user.id,title:f.title,description:f.description||null,price:Number(f.price),quantity:Number(f.quantity),category_id:f.category_id||null,location:f.location||null,images:f.image?[f.image]:[],status:"active"});setBusy(false);if(r.error)notice(r.error.message);else{notice("Your listing is live.");setF({title:"",description:"",price:"",quantity:"1",category_id:"",location:"",image:""});await refresh();goActivity()}};return <main className="page narrow"><span className="eyebrow">CREATE A LISTING</span><h1>Sell something useful.</h1><p className="lead">Clear information helps another student decide faster.</p><form className="formCard" onSubmit={submit}><label>Listing title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="e.g. Scientific calculator"/></label><label>Description<textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})} placeholder="Condition, size, what is included…"/></label><div className="two"><label>Price (GHS)<input required type="number" min="0" step=".01" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/></label><label>Quantity<input required type="number" min="1" value={f.quantity} onChange={e=>setF({...f,quantity:e.target.value})}/></label></div><div className="two"><label>Category<select value={f.category_id} onChange={e=>setF({...f,category_id:e.target.value})}><option value="">Choose category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Location<input value={f.location} onChange={e=>setF({...f,location:e.target.value})} placeholder="Campus / area"/></label></div><label>Image URL <em>optional</em><input type="url" value={f.image} onChange={e=>setF({...f,image:e.target.value})} placeholder="https://…"/></label><button className="primary" disabled={busy}>{busy?"Publishing…":"Publish listing →"}</button></form></main>}

function Activity({session}:{session:any}){const[data,setData]=useState<any[]>([]);useEffect(()=>{if(session)supabase.from("orders").select("id,quantity,total_amount,status,created_at,listings(title)").eq("buyer_id",session.user.id).order("created_at",{ascending:false}).then(r=>setData(r.data||[]))},[session]);if(!session)return <main className="page"><div className="empty"><b>Your activity is private.</b><span>Sign in to view your orders.</span></div></main>;return <main className="page"><span className="eyebrow">YOUR ACTIVITY</span><h1>Orders</h1><p className="lead">Keep track of purchases made through the marketplace.</p><div className="orderList">{data.length?data.map(o=><div className="order" key={o.id}><div><b>{o.listings?.title||"Order"}</b><small>#{String(o.id).slice(0,8)} · {new Date(o.created_at).toLocaleDateString()}</small></div><strong>{money(o.total_amount)}</strong><span>{o.status}</span></div>):<div className="empty"><b>No orders yet.</b><span>Your purchases will appear here.</span></div>}</div></main>}

function Saved({listings,open,save}:{listings:Listing[];open:(l:Listing)=>void;save:(id:string)=>void}){return <main className="page"><span className="eyebrow">YOUR PICKS</span><h1>Saved</h1><p className="lead">Listings you want to come back to.</p>{listings.length?<div className="marketGrid">{listings.map(l=><Product key={l.id} l={l} saved save={()=>save(l.id)} open={()=>open(l)}/>)}</div>:<div className="empty"><b>Your saved list is empty.</b><span>Tap the heart on a listing to keep it here.</span></div>}</main>}

function Profile({session,notice,signOut,goActivity}:{session:any;notice:(s:string)=>void;signOut:()=>void;goActivity:()=>void}){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[signup,setSignup]=useState(false),[busy,setBusy]=useState(false);if(session)return <main className="page narrow"><div className="profileCard"><span className="profileAvatar">{(session.user.email||"S")[0].toUpperCase()}</span><span className="eyebrow">YOUR ACCOUNT</span><h1>{session.user.user_metadata?.full_name||"Student account"}</h1><p>{session.user.email}</p><button className="outline" onClick={goActivity}>View orders</button><button className="danger" onClick={signOut}>Sign out</button></div></main>;const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);const r=signup?await supabase.auth.signUp({email,password,options:{data:{full_name:name}}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(r.error)notice(r.error.message);else notice(signup?"Account created.":"Signed in.")};return <main className="page narrow"><div className="authCard"><span className="mark">SB</span><span className="eyebrow">{signup?"CREATE YOUR ACCOUNT":"WELCOME BACK"}</span><h1>{signup?"Join the marketplace.":"Your campus, connected."}</h1><p>Buy, sell and keep your student marketplace activity in one place.</p><form className="formCard flat" onSubmit={submit}>{signup&&<label>Name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></label><button className="primary" disabled={busy}>{busy?"Please wait…":signup?"Create account →":"Sign in →"}</button></form><button className="textBtn" onClick={()=>setSignup(!signup)}>{signup?"Already have an account? Sign in":"New here? Create an account"}</button></div></main>}
